import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar/Navbar'
import Footer from '@/components/Footer/Footer'
import NotFound from './not-found'
import { Providers } from './providers'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { LocaleProvider } from '@/LocaleContext'
import { NextIntlClientProvider } from 'next-intl'
import { ThemeProvider } from '@/components/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'it', 'fr', 'de', 'pt', 'cn', 'kr', 'jp'];

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {

  if (!locale || !locales.includes(locale)) {
    NotFound()
  }

  let messages;

  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    NotFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers>
          <LocaleProvider locale={locale}>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange >
              <Navbar locale={locale} />
              <div className='layout-container'>
                {children}
                <ToastContainer />
              </div>
              <Footer />
              </ThemeProvider>
            </NextIntlClientProvider>
          </LocaleProvider>
        </Providers>
      </body>
    </html>
  )
}
